# Pre-deploy script to inject API URL into frontend build
# This runs before Docker build, making the URL available at build time

$ErrorActionPreference = "Stop"

Write-Host "Preparing frontend environment for deployment..." -ForegroundColor Green

# Get the root directory (two levels up from the script)
$ROOT_DIR = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$FRONTEND_DIR = Join-Path $ROOT_DIR "src/agentic-ui"
$ENV_FILE = Join-Path $FRONTEND_DIR ".env.production.local"

# Read environment variables from azd
$azdEnvOutput = azd env get-values
$envVars = @{}
foreach ($line in $azdEnvOutput) {
    if ($line -match '^([^=]+)=(.*)$') {
        $envVars[$matches[1]] = $matches[2] -replace '^"?(.*?)"?$', '$1'
    }
}

$AGENT_API_URL = ""

# Get the Container Apps Environment default domain
$CONTAINER_ENV_DOMAIN = if ($envVars.ContainsKey('AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN')) { 
    $envVars['AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN'] 
} else { "" }

# If not set, try to get from Azure directly
if ([string]::IsNullOrEmpty($CONTAINER_ENV_DOMAIN)) {
    # Get the API Container App FQDN if available
    $API_FQDN = if ($envVars.ContainsKey('AZURE_CONTAINER_APP_AGENTIC_API_FQDN')) { 
        $envVars['AZURE_CONTAINER_APP_AGENTIC_API_FQDN'] 
    } else { "" }
    
    if (-not [string]::IsNullOrEmpty($API_FQDN)) {
        $AGENT_API_URL = "https://$API_FQDN"
    } else {
        # Fallback: try to get from Azure CLI
        $RESOURCE_GROUP = if ($envVars.ContainsKey('AZURE_RESOURCE_GROUP')) { 
            $envVars['AZURE_RESOURCE_GROUP'] 
        } else { "" }
        
        if (-not [string]::IsNullOrEmpty($RESOURCE_GROUP)) {
            try {
                Write-Host "Fetching API Container App FQDN from Azure..." -ForegroundColor Cyan
                $API_FQDN = az containerapp show `
                    --name agentic-api `
                    --resource-group $RESOURCE_GROUP `
                    --query "properties.configuration.ingress.fqdn" `
                    --output tsv 2>$null
                
                if (-not [string]::IsNullOrEmpty($API_FQDN)) {
                    $AGENT_API_URL = "https://$API_FQDN"
                }
            } catch {
                Write-Host "Could not fetch Container App FQDN: $_" -ForegroundColor Yellow
            }
        }
    }
}

# If we still don't have the URL, try to get the default domain
if ([string]::IsNullOrEmpty($AGENT_API_URL)) {
    $RESOURCE_GROUP = if ($envVars.ContainsKey('AZURE_RESOURCE_GROUP')) { 
        $envVars['AZURE_RESOURCE_GROUP'] 
    } else { "" }
    
    if (-not [string]::IsNullOrEmpty($RESOURCE_GROUP)) {
        try {
            $DEFAULT_DOMAIN = az containerapp env list `
                --resource-group $RESOURCE_GROUP `
                --query "[0].properties.defaultDomain" `
                --output tsv 2>$null
            
            if (-not [string]::IsNullOrEmpty($DEFAULT_DOMAIN)) {
                $AGENT_API_URL = "https://agentic-api.$DEFAULT_DOMAIN"
            }
        } catch {
            Write-Host "Could not fetch Container Apps Environment domain: $_" -ForegroundColor Yellow
        }
    }
}

# Validate we have a URL
if ([string]::IsNullOrEmpty($AGENT_API_URL)) {
    Write-Host "Warning: Could not determine AGENT_API_URL. Frontend will use runtime environment variable." -ForegroundColor Yellow
    Write-Host "The server-side proxy routes will still work with AGENT_API_URL set at container runtime." -ForegroundColor Yellow
    exit 0
}

# Write the environment file for the frontend build
Write-Host "Writing API URL to frontend environment file..." -ForegroundColor Cyan

$envContent = @"
# Auto-generated by predeploy script
# This file is used during the Next.js build process

# Server-side API URL (used by API routes/proxy)
AGENT_API_URL=$AGENT_API_URL

# Client-side API URL (if needed for direct client calls)
# Uncomment if you want client-side code to call the API directly
# NEXT_PUBLIC_AGENT_API_URL=$AGENT_API_URL
"@

Set-Content -Path $ENV_FILE -Value $envContent

Write-Host "Frontend environment configured successfully!" -ForegroundColor Green
Write-Host "  - AGENT_API_URL: $AGENT_API_URL" -ForegroundColor Cyan
Write-Host "  - Environment file: $ENV_FILE" -ForegroundColor Cyan
