#!/bin/bash

# Pre-deploy script to inject API URL into frontend build
# This runs before Docker build, making the URL available at build time

set -e

echo -e "\033[0;32mPreparing frontend environment for deployment...\033[0m"

# Get the root directory (two levels up from the script)
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FRONTEND_DIR="$ROOT_DIR/src/agentic-ui"
ENV_FILE="$FRONTEND_DIR/.env.production.local"

# Read environment variables from azd
eval "$(azd env get-values)"

# Get the Container Apps Environment default domain
# This is output by the resources.bicep as part of the Container App URLs
CONTAINER_ENV_DOMAIN="${AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN:-}"

# If not set, try to construct from resource group info
if [ -z "$CONTAINER_ENV_DOMAIN" ]; then
    # Get the API Container App FQDN if available
    API_FQDN="${AZURE_CONTAINER_APP_AGENTIC_API_FQDN:-}"
    
    if [ -n "$API_FQDN" ]; then
        AGENT_API_URL="https://$API_FQDN"
    else
        # Fallback: construct from environment name pattern
        # Container Apps URLs follow: https://<app-name>.<env-default-domain>
        RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-}"
        if [ -n "$RESOURCE_GROUP" ]; then
            # Try to get the FQDN using Azure CLI
            if command -v az &> /dev/null; then
                echo -e "\033[0;36mFetching API Container App FQDN from Azure...\033[0m"
                API_FQDN=$(az containerapp show \
                    --name agentic-api \
                    --resource-group "$RESOURCE_GROUP" \
                    --query "properties.configuration.ingress.fqdn" \
                    --output tsv 2>/dev/null || echo "")
                
                if [ -n "$API_FQDN" ]; then
                    AGENT_API_URL="https://$API_FQDN"
                fi
            fi
        fi
    fi
fi

# If we still don't have the URL, use the known pattern from Bicep
if [ -z "$AGENT_API_URL" ]; then
    # The Bicep constructs: https://agentic-api.${containerAppsEnvironment.outputs.defaultDomain}
    # We can get the default domain from any existing container app
    RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-}"
    if [ -n "$RESOURCE_GROUP" ] && command -v az &> /dev/null; then
        DEFAULT_DOMAIN=$(az containerapp env list \
            --resource-group "$RESOURCE_GROUP" \
            --query "[0].properties.defaultDomain" \
            --output tsv 2>/dev/null || echo "")
        
        if [ -n "$DEFAULT_DOMAIN" ]; then
            AGENT_API_URL="https://agentic-api.$DEFAULT_DOMAIN"
        fi
    fi
fi

# Validate we have a URL
if [ -z "$AGENT_API_URL" ]; then
    echo -e "\033[0;33mWarning: Could not determine AGENT_API_URL. Frontend will use runtime environment variable.\033[0m"
    echo -e "\033[0;33mThe server-side proxy routes will still work with AGENT_API_URL set at container runtime.\033[0m"
    exit 0
fi

# Write the environment file for the frontend build
echo -e "\033[0;36mWriting API URL to frontend environment file...\033[0m"

cat > "$ENV_FILE" << EOF
# Auto-generated by predeploy script
# This file is used during the Next.js build process

# Server-side API URL (used by API routes/proxy)
AGENT_API_URL=$AGENT_API_URL

# Client-side API URL (if needed for direct client calls)
# Uncomment if you want client-side code to call the API directly
# NEXT_PUBLIC_AGENT_API_URL=$AGENT_API_URL
EOF

echo -e "\033[0;32mFrontend environment configured successfully!\033[0m"
echo -e "\033[0;36m  - AGENT_API_URL: $AGENT_API_URL\033[0m"
echo -e "\033[0;36m  - Environment file: $ENV_FILE\033[0m"
